# Generated by Django 4.1.5 on 2023-07-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemModel',
            new_name='OrderItems',
        ),
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='ProductsModel',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='ShippingAddressModel',
            new_name='ShippingAddress',
        ),
    ]
