# Generated by Django 4.1.5 on 2023-07-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_orderitemmodel_orderitems_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
